// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Represents a page number in a book.
 */
public class PageNumber {
    @JsonValue
    private UnsignedShort value;

    public PageNumber() {
    }

    @JsonCreator
    public PageNumber(UnsignedShort value) {
        this.value = value;
    }

    public UnsignedShort getValue() {
        return value;
    }

    public void setValue(UnsignedShort value) {
        this.value = value;
    }
}
