// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A rich text string in Markdown with replaced values from oracle roll
    /// results.
    /// 
    /// The custom syntax `{{some_row_key>some_oracle_table_id}}`
    /// should be replaced by the `some_row_key` string of a rolled
    /// oracle table. This is usually the `text` key, for example
    /// `{{text>oracle_rollable:starforged/core/action}}`
    /// </summary>
    [JsonConverter(typeof(MarkdownTemplateStringJsonConverter))]
    public class MarkdownTemplateString
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public string Value { get; set; }
    }

    public class MarkdownTemplateStringJsonConverter : JsonConverter<MarkdownTemplateString>
    {
        public override MarkdownTemplateString Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new MarkdownTemplateString { Value = JsonSerializer.Deserialize<string>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, MarkdownTemplateString value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<string>(writer, value.Value, options);
        }
    }
}
